### ISSUE TITLE
World Legacy Inheritor

### ISSUE THREAD

**Issue by kenpazaraki** [Ygoproco/Live2017Links#354] opened 2018-01-21 10:28 UTC
It looks like World Legacy Inheritor can't be activated when the only free zone where the target could be summoned is an Extra Monster Zone, despite the fact that it should be possible if the target is a Link Monster (unless there's a ruling I'm unaware of).

**Comment by EerieCode** [comment] 2018-01-21 10:41
It's not a bug: only monsters summoned from the Extra Deck can go to the Extra Monster Zone. If you're summoning a monster from the Graveyard, then it always goes to a Main Monster Zone.

**Comment by kenpazaraki** [comment] 2018-01-21 10:51
It's bugged anyway, since it allows to summon a monster in an Extra Monster Zone if it's a Link Monster and there are at least a Main Monster Zone and an Extra Monster Zone available.

**Comment by EerieCode** [comment] 2018-01-21 12:39
I think I see the issue now: the script specifically excludes the EMZ in the target, but not in the operation. I've uploaded a patch to fix it, so we can close the issue now. Thanks for the report!

**Closed by EerieCode** 2018-01-21 12:39 UTC
